name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Extract Tag
        id: meta
        run: echo "tag=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install deps
        run: npm ci
      - name: Build dist
        run: npm run build:dist
      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker metadata
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/approval-service
          tags: |
            type=raw,value=${{ steps.meta.outputs.tag }}
            type=raw,value=latest
      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/${{ github.repository_owner }}/approval-service:${{ steps.meta.outputs.tag }}
          format: table
          ignore-unfixed: true
          vuln-type: 'os,library'
          exit-code: '1'
        continue-on-error: true
      - name: Output Image Reference
        run: echo "Published ghcr.io/${{ github.repository_owner }}/approval-service:${{ steps.meta.outputs.tag }}"